server:
  port: 9100
spring:
  application:
    name: user-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 101.132.136.153:8849
  datasource:
    data-username: root
    data-password: 123456
    url: jdbc:mysql://106.14.127.161:8066/NJWEBDB
    driver-class-name: com.mysql.jdbc.Driver
