server:
  port: 8001
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 101.132.136.153:8848
    gateway:
      discovery:
        locator:
          enabled: true
      enabled: true   #开启
