server:
  port: 9120
spring:
  application:
    name: zookeeper-curator
  datasource:
    data-username: root
    data-password: 123456
    url: jdbc:mysql://106.14.127.161:8066/NJWEBDB
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.sunny.zookeepercurator.dao
  configuration:
    map-underscore-to-camel-case: true